# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Homework 12' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework 12
pod 'Alamofire'
pod 'SVProgressHUD'

end
