# Uncomment the next line to define a global platform for your project
 platform :ios, '13.3'

target 'Homework 14' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  use_modular_headers!

  # Pods for Homework 14
pod 'Alamofire', '~> 5.0'
pod 'RealmSwift'

end
